// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHWevwL55KHsTK_H6n28VBaKWuBDhRgWQ',
    appId: '1:900129137467:web:b434fa6ababd514f840d1e',
    messagingSenderId: '900129137467',
    projectId: 'ppb-firebase-4dbcc',
    authDomain: 'ppb-firebase-4dbcc.firebaseapp.com',
    storageBucket: 'ppb-firebase-4dbcc.firebasestorage.app',
    measurementId: 'G-RREWHLDN5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwp6EWMBvQyS4Gf5FFnWV5jJfUpVTugsI',
    appId: '1:900129137467:android:8bd38b969250491a840d1e',
    messagingSenderId: '900129137467',
    projectId: 'ppb-firebase-4dbcc',
    storageBucket: 'ppb-firebase-4dbcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-0glZ1Sha2p9uudJKEM8btgzzETE4Wo',
    appId: '1:900129137467:ios:14c8be5072c1b221840d1e',
    messagingSenderId: '900129137467',
    projectId: 'ppb-firebase-4dbcc',
    storageBucket: 'ppb-firebase-4dbcc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-0glZ1Sha2p9uudJKEM8btgzzETE4Wo',
    appId: '1:900129137467:ios:14c8be5072c1b221840d1e',
    messagingSenderId: '900129137467',
    projectId: 'ppb-firebase-4dbcc',
    storageBucket: 'ppb-firebase-4dbcc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHWevwL55KHsTK_H6n28VBaKWuBDhRgWQ',
    appId: '1:900129137467:web:5d8083292078a474840d1e',
    messagingSenderId: '900129137467',
    projectId: 'ppb-firebase-4dbcc',
    authDomain: 'ppb-firebase-4dbcc.firebaseapp.com',
    storageBucket: 'ppb-firebase-4dbcc.firebasestorage.app',
    measurementId: 'G-S7B6LBHPFB',
  );
}
